package:
  name: yyjson
  version: 0.10.0
  epoch: 0
  description: High performance JSON library in C
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - ninja-build
      - pkgconf

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ibireme/yyjson.git
      tag: 0.10.0
      depth: 1

  - uses: cmake/configure
    with:
      opts: |
        -DYYJSON_BUILD_SHARED_LIBS=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: yyjson-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - yyjson # melange

update:
  enabled: false
