package:
  name: astal-powerprofiles
  version: 0.1.0
  epoch: 0
  description: DBus proxy for upowerd profiles
  copyright:
    - license: LGPL-2.1-only
  dependencies:
    runtime:
      - glib
      - json-glib # melange

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - meson
      - ninja-build
      - pkgconf
      - python-3.13
      - vala
      - json-glib-dev # melange

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aylur/astal.git
      branch: main
      depth: 1

  # Every Astal library is its own meson project inside the monorepo.
  - working-directory: lib/powerprofiles
    pipeline:
      - uses: meson/configure
        with:
          opts: |
            -Dbuildtype=debugoptimized

      - uses: meson/compile

      - uses: meson/install

  - uses: strip

subpackages:
  - name: astal-powerprofiles-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - astal-powerprofiles # melange
        - glib-dev
        - json-glib-dev # melange

update:
  enabled: false
